### ISSUE TITLE
Breaks on single backtick in commit message

### ISSUE THREAD

**Issue by max-sixty** [xarray-contrib/ci-trigger#4]
FYI the action breaks on a single backtick in a commit message, for example: https://github.com/pydata/xarray/actions/runs/6242743778/job/16947141657?pr=8216#step:3:25

The commit message was:

```
And `DataWithCoords
```

...I had missed the ending backtick

I doubt it's super important... (though possibly it means it can execute code from a commit message? Is that security risk if it's running with secrets? Seems remote but FYI)...

**Comment by keewis** [comment]
The issue is that in a final step I'm using `echo` to print the commit message. However, because the GA variables are expanded *before* handing it to the shell, which will try to expand them, resulting in the error you're seeing.

To avoid this, I think we can use environment variables. I'll send in a PR.

**Comment by keewis** [comment]
should be fine now, see https://github.com/keewis/test-project/actions/runs/6245392519/job/16953955011

**Comment by max-sixty** [comment]
Thanks so much!

**Comment by keewis** [comment]
I also decided to publish `v1.x.1` versions of all releases, because I saw that at least some projects pin the action without having dependabot enabled (not sure if those will be picked up, though)
